### ISSUE TITLE
KPI Hierarchy Aggregation/Calculation Strategy Review

### ISSUE THREAD

**Issue by BenedictWohlers87** [fraunhofer-iem/software-product-health-analyzer#29]
We currently foresee the following data aggregation strategies:
- (Weighted) average:
The average sums the values of each input and then divides by the number of inputs - the result is passed to the parent node. The weighted average multiplies each input by a specific weight and adds up the results in order to divide them by the number of inputs. Care should be taken to ensure that the weights do not cause the final value to leave the value range [0..100] (sum of weights = 1). The final result is passed to the higher-level node.
- (Weighted) minimum
The minimum determines the lowest value from all inputs and passes this on to the higher-level node. For the weighted minimum, the individual inputs are offset with a specific weight before the minimum is determined. As the final result, the actual value of the input value with the lowest weighted value is passed on to the higher-level node. 
- (Weighted) maximum
The maximum determines the highest value from all inputs and passes this on to the higher-level node. For the weighted maximum, the individual inputs are offset with a specific weight before the maximum is determined. As the final result, the actual value of the input with the highest weighted value is passed on to the higher-level node. 
- (Weighted) ratio
The ratio is formed by dividing two inputs and passed on to the higher-level node as the result. It is important to ensure that the inputs have the same dimension and that the result lies within the value range [0..100]. The weighted ratio combines divisors and denominators with a specific weight before the ratio is determined by division and passed on to the higher-level node as the result. It must be ensured that the result lies within the value range [0..100].
- Binary decisions (AND, OR, XOR)
AND, OR and XOR check the inputs for “true” or 100 or “false” or 0. The following applies to AND: If all inputs show the value “true” or 100, “true” or 100 is passed on to the higher-level node.
The following applies to AND: If at least one of the inputs shows the value “true” or 100, “true” or 100 is passed on to the higher-level node. 
The following applies to XOR: Expects exactly two inputs and forwards “true” or 100 to the higher-level node if only one of the two inputs has this value.

Are all these strategies implemented in the correct way? Are there any strategies missing? Do we really need weights in the first place or do we only need them in the adapter step?

**Comment by janniclas** [comment]
* Weighted average should be kept as it is. However, we'll add an inRange check to all KPI results to ensure their correctness, if, for what ever reason, they run out of bounds (<0 or <100)
